apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-convo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-convo1
  template:
    metadata:
      labels:
        app: chatbot-convo1
    spec:
      containers:
        - name: convo-api
          image: 239065919983.dkr.ecr.us-east-1.amazonaws.com/chatbotfrontend:convo_new
          ports:
            - containerPort: 8000
        
