apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-global1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-global1
  template:
    metadata:
      labels:
        app: chatbot-global1
    spec:
      containers:
        - name: global-api
          image: 239065919983.dkr.ecr.us-east-1.amazonaws.com/chatbotfrontend:global_new
          ports:
            - containerPort: 7000

        
