apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-frontend
  template:
    metadata:
      labels:
        app: chatbot-frontend
    spec:
      containers:
        - name: front-end
          image: 239065919983.dkr.ecr.us-east-1.amazonaws.com/chatbotfrontend:frontendlatest5
          ports:
            - containerPort: 3000
